name: Nuget Publish

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish Agent API
      uses: rohith/publish-nuget@v2.5.6
      with:
        PROJECT_FILE_PATH: src/Ragnarok.AgentApi/Ragnarok.AgentApi.csproj
        VERSION_FILE_PATH: Directory.Build.props
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: false
    - name: Publish Hosted Service
      uses: rohith/publish-nuget@v2.5.6
      with:
        PROJECT_FILE_PATH: src/Ragnarok.HostedService/Ragnarok.HostedService.csproj
        VERSION_FILE_PATH: Directory.Build.props
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: false
